# Generated by Django 3.1.1 on 2020-09-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0002_auto_20200914_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(default=None, related_name='games', to='gaming.Platform'),
        ),
    ]
