# Generated by Django 3.1.1 on 2020-09-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0005_auto_20200915_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
