# Generated by Django 3.1.1 on 2020-09-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0006_auto_20200915_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_owned',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_wishlist',
        ),
    ]
