# Generated by Django 3.1.1 on 2020-09-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0010_auto_20200916_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
    ]
