# Generated by Django 3.1.1 on 2020-09-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0014_auto_20200916_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
