# Generated by Django 3.1.1 on 2020-09-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0016_game_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='brand',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
