# Generated by Django 3.1.1 on 2020-09-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0017_platform_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='brand',
            field=models.CharField(max_length=55),
        ),
    ]
