# Generated by Django 3.1.1 on 2020-09-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(to='gaming.Game'),
        ),
        migrations.AddField(
            model_name='user',
            name='platforms',
            field=models.ManyToManyField(to='gaming.Platform'),
        ),
    ]
