# Generated by Django 3.1.1 on 2020-09-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0005_auto_20200915_1445'),
        ('authentication', '0002_auto_20200914_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(default=None, to='gaming.Game'),
        ),
    ]
