# Generated by Django 3.1.1 on 2020-09-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0007_auto_20200915_1646'),
        ('authentication', '0003_auto_20200915_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watch_list',
            field=models.ManyToManyField(default=None, related_name='watcher', to='gaming.Game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(default=None, related_name='owned', to='gaming.Game'),
        ),
    ]
